### Tomcat

tomcat:
    image: menski/camunda-bpm-platform:tomcat-7.4.0
    ports:
        - "8080:8080"

tomcat-mysql:
    extends:
        service: tomcat
    environment:
        - DB_DRIVER=com.mysql.jdbc.Driver
        - DB_URL=jdbc:mysql://db:3306/process-engine
        - DB_USERNAME=camunda
        - DB_PASSWORD=camunda
        - WAIT_FOR=db:3306
    links:
        - mysql:db

tomcat-postgresql:
    extends:
        service: tomcat
    environment:
        - DB_DRIVER=org.postgresql.Driver
        - DB_URL=jdbc:postgresql://db:5432/process-engine
        - DB_USERNAME=camunda
        - DB_PASSWORD=camunda
        - WAIT_FOR=db:5432
    links:
        - postgresql:db


### JBoss

jboss:
    image: menski/camunda-bpm-platform:jboss-7.4.0
    ports:
        - "8080:8080"

jboss-mysql:
    extends:
        service: jboss
    environment:
        - DB_DRIVER=com.mysql.jdbc.Driver
        - DB_URL=jdbc:mysql://db:3306/process-engine
        - DB_USERNAME=camunda
        - DB_PASSWORD=camunda
        - WAIT_FOR=db:3306
    links:
        - mysql:db

jboss-postgresql:
    extends:
        service: jboss
    environment:
        - DB_DRIVER=org.postgresql.Driver
        - DB_URL=jdbc:postgresql://db:5432/process-engine
        - DB_USERNAME=camunda
        - DB_PASSWORD=camunda
        - WAIT_FOR=db:5432
    links:
        - postgresql:db


### WildFly

wildfly:
    image: menski/camunda-bpm-platform:wildfly-7.4.0
    ports:
        - "8080:8080"

wildfly-mysql:
    extends:
        service: wildfly
    environment:
        - DB_DRIVER=com.mysql.jdbc.Driver
        - DB_URL=jdbc:mysql://db:3306/process-engine
        - DB_USERNAME=camunda
        - DB_PASSWORD=camunda
        - WAIT_FOR=db:3306
    links:
        - mysql:db

wildfly-postgresql:
    extends:
        service: wildfly
    environment:
        - DB_DRIVER=org.postgresql.Driver
        - DB_URL=jdbc:postgresql://db:5432/process-engine
        - DB_USERNAME=camunda
        - DB_PASSWORD=camunda
        - WAIT_FOR=db:5432
    links:
        - postgresql:db


### GlassFish

glassfish:
    image: menski/camunda-bpm-platform:glassfish-7.4.0
    ports:
        - "8080:8080"

glassfish-mysql:
    extends:
        service: glassfish
    environment:
        - DB_DRIVER=com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        - DB_URL=jdbc:mysql://db:3306/process-engine
        - DB_USERNAME=camunda
        - DB_PASSWORD=camunda
        - WAIT_FOR=db:3306
    links:
        - mysql:db

glassfish-postgresql:
    extends:
        service: glassfish
    environment:
        - DB_DRIVER=org.postgresql.ds.PGSimpleDataSource
        - DB_URL=jdbc:postgresql://db:5432/process-engine
        - DB_USERNAME=camunda
        - DB_PASSWORD=camunda
        - WAIT_FOR=db:5432
    links:
        - postgresql:db


### Databases

mysql:
    image: mysql:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=camunda
        - MYSQL_USER=camunda
        - MYSQL_PASSWORD=camunda
        - MYSQL_DATABASE=process-engine

postgresql:
    image: postgres:9.3
    environment:
        - POSTGRES_USER=camunda
        - POSTGRES_PASSWORD=camunda
        - POSTGRES_DB=process-engine
